# params for the slider
mu: 0.35
mu_g: 0.30
m: 0.25
length: 0.09 # along x direction 
width: 0.105 # along y direction
mMax: 0.0275 # numerical integrated

# params for MPC
n_step: 20
t_step: 0.05
QFinal: 2000.0
Q: 10.0
R: 0.5

# debug
debug_info: true